#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAndroidBasicApplication.Resource", IsApplication=true)]

namespace XamarinAndroidBasicApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backWhite = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int ColorSetsImageBack = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int ColorSetsImageNext = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int ColorSetsName = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int ColorSetsView = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int MenuBasicMultiPageScreen = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int MenuBasicSinglePageScreen = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int MultiScreenImageBack = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int MultiScreenPhoneNumberText = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int MultiScreenTextPhoneWord = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int MultiScreenTranslateButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int MultiScreenTranslatedPhoneWord = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int PhoneNumberText = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int SingleAXMLFromMultipleActivites = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int SingleScreenImageBack = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int TranslateButton = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int TranslatedPhoneWord = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int TranslationHistoryButton = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout1 = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int scrollView1 = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int textPhoneWord = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HelloDroidMultiScreenAXML = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HelloDroidSingleScreenAXML = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainMenuActivityAXML = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SingleAXMLForMultiActivities = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int translationHistory = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
